// CarClient/src/CarList.jsx
//@ts-check
import React, {useState} from "react"; 


function CarList({name, data, onCreate, onUpdate, onDelete, error}){
    
    console.log(data)



    const [formData, setFormData] = useState(
        {id: '', brand: "", model: "", 
            year: null, reserved: false, price: null
        });
    const [editingId, setEditingId] = useState(null);
    const [selectedOption, setSelectedOption] = useState(null);

    const handleFormChange = (event) => {
        const {name, value} = event.target;
        
        setFormData(prevData => ({
            ...prevData, [name]: value
        }));
        setSelectedOption(formData.reserved);
    };

    const handleSubmit = (event) =>  {
        event.preventDefault();
        console.log(formData);
        if (editingId) {
            if (selectedOption === "true"){
                formData.reserved = true;
            }else {
                formData.reserved = false;
            }
            onUpdate(formData);
            setEditingId(null);
        } else {
            onCreate(formData);
        }
        setFormData({id: '', brand: "", model: "", 
            year: null, reserved: false, price: null
        });
    }

    const handleEdit = (item) => {
        setEditingId(item.id);
        setFormData({
            id: item.id, brand: item.brand, model: item.model, 
            year: item.year, reserved: item.reserved, price: item.price
        });
    };

    const handleCancelEdit = () => {
        setEditingId(null);
        setFormData({id: '', brand: "", model: "", 
            year: null, reserved: false, price: null
        });
    }

    return (
        <div>
            <h2>New {name}</h2>
            <form onSubmit={handleSubmit}>
                <input
                    type="text"
                    name="brand"
                    placeholder="Brand"
                    value={formData.brand}
                    onChange={handleFormChange}
                />
                <input
                    type="text"
                    name="model"
                    placeholder="Model"
                    value={formData.model}
                    onChange={handleFormChange}
                />
                <input
                    type="text"
                    name="year"
                    placeholder="Year"
                    value={formData.year === null ? "": formData.year}
                    onChange={handleFormChange}
                />
                <input
                    type="text"
                    name="price"
                    placeholder="Price"
                    value={formData.price === null? "": formData.price}
                    onChange={handleFormChange}
                    />
                <select
                    name="reserved"
                    value={selectedOption}
                    onChange={handleFormChange}
                >
                    <option>Choose an option</option>
                    <option value={"true"}>reserved</option>
                    <option value={"false"}>available</option>
                </select>
                <button type="submit">{ editingId ? ' Update' : 'Create'}</button>
                {editingId && <button type="button" onClick={handleCancelEdit}>Cancel</button>}
            </form>
            {error && <div>{error.message}</div>}
            <h2>{name}</h2>
            <ul>
                {data.map(item => (
                    <li key={item.id}>
                        <div>{item.brand} - {item.model} - {item.year} - {item.price} - {item.reserved === true? "Available": "Unavailable"}</div>
                        <div>
                            <button onClick={() => handleEdit(item)}>Edit</button>
                            <button onClick={() => onDelete(item.id)}> Delete</button>
                        </div>
                    </li>
                ))}
            </ul>
            
        </div>
    );
}

export default CarList;

// Car-Frontend/src/app/car-list/car-list.component.ts
import { Component, Input } from '@angular/core';
import { CarInterface } from '../car-interface';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-car-list',
  standalone: true,
  imports: [DatePipe],
  templateUrl: './car-list.component.html',
  styleUrl: './car-list.component.css'
})
export class CarListComponent {
  car:CarInterface = {
    id: -1,
    brand: "",
    model: "",
    year: this.formatDateToYYYMMDD(new Date()),
    price: 0,
    reserved: undefined
  };
  @Input() carlist: Array<CarInterface> = [];
  @Input() listTitle: string="";
  
  
  formatDateToYYYMMDD(date:Date) {
    const d = new Date(date);
    let month = ''+ (d.getMonth()+1),
        day = '' + d.getDate(),
        year = d.getFullYear();

    if (month.length < 2 ) month = '0' + month;
    if (day.length < 2) day = '0'+ day;

    return [year, month, day].join('-')
  }


  handleFormChange($event: Event): void {
    const { name, value } = $event.target as HTMLInputElement;
    // Rest of the code...
    switch (name) {
      case "model":
          this.car.model = value;
        break;
      case "brand":
          this.car.brand = value;
        break;
        case "price":
          this.car.price = parseInt(value);
        break;
        case "year":
        
          this.car.year = this.formatDateToYYYMMDD(new Date(value));
        break;
        case "reserved":
          this.car.reserved = value === "true" ? true : false;
          break;
      default:
        console.log("Fallthrough: "+ name + ":"+ value);
        break;
    }
    console.log("onchange: " + JSON.stringify(this.car))
  }


  handleSubmit($event:Event){
    $event.preventDefault();
    if (this.car.id >0){
      this.carlist = this.carlist.map(item => item.id === this.car.id ? this.car: item);
      console.log("car updated: " + JSON.stringify(this.car))
    }else {
      this.car.id = this.carlist.length+1;
      this.carlist.push(this.car);
      console.log("Car created: "+ JSON.stringify(this.car))
    }
    this.car = {id: -1, brand: "", model: "", year: this.formatDateToYYYMMDD(new Date()), price: 0, reserved: undefined};
  }

  onEdit(id: number) {
    const result = this.carlist.find(car => car.id === id);
    if (result === undefined) this.car = {id: -1,brand: "", model: "", year: new Date(), price: 0, reserved: undefined};
    else this.car = {...result}; //always forget about the referencial. Always create a shallow copy else you also reference the array.
    if (typeof this.car.year !== "string" ) this.car.year= this.formatDateToYYYMMDD(this.car.year);

  }

  onDelete(id: number) {
   this.carlist= this.carlist.filter(car => car.id !== id);
  }

  onCancel($event: Event): void {
    $event.preventDefault();
    this.car = {
      brand: "", model: "", id: -1, year: new Date(), price: 0, reserved: undefined
    }
  }
}

<div>
    <form (submit)="handleSubmit($event)" method="POST">
        <input type="text" [value]="car.brand" name="brand" placeholder="Brand" (change)="handleFormChange($event)">
        <input type="text" [value]="car.model" name ="model" placeholder="Model" (change)="handleFormChange($event)">  
        <input type="text" [value]="car.price" name ="price" placeholder="Price" (change)="handleFormChange($event)">  
        <input type="date" [value]="car.year" name="year" placeholder="Year" (change)="handleFormChange($event)">
        <select name="reserved" [value]="car.reserved" (change)="handleFormChange($event)">
            <option value="">Choose a selection</option>
            <option value="false">Available</option>
            <option value="true">Unavailable</option>
        </select>
        @if(car.id > 0){
            <button type="submit">Edit</button>
        } @else {
            <button type="submit">Create</button>
        }
        <button (click)="onCancel($event)">Cancel</button>
    </form>
    <h2>{{listTitle}}</h2>
    @for (car of carlist; track car.id){
        <ul>
            <li>{{car.brand}}</li>
            <li>{{car.model}}</li>
            <li>{{car.price}}</li>
            <li>{{car.year | date }}</li>
            <li>{{car.reserved}}</li>
            <li>
                <button (click)="onEdit(car.id)">Edit</button>
                <button (click)="onDelete(car.id)">Delete</button>
            </li>
        </ul>
    }
</div>
